@extends('errors.layout')
@section('code', '403')
@section('emoji', '🚧')
@section('title', 'This gate is closed')
@section('message', "You don't have permission to view this page. If you think this is a mistake, please contact support.")
