@extends('errors.layout')
@section('code', '403')
@section('emoji', '🚧')
@section('title', 'You cannot open this page')
@section('message', "Your account does not have access to this page. If you think this is a mistake, please contact support.")
