@extends('errors.layout')
@section('code', '404')
@section('emoji', '🧭')
@section('title', 'Page not found')
@section('message', "We could not find this page. It may have moved, or the link may have a typo.")
