@extends('errors.layout')
@section('code', '404')
@section('emoji', '🧭')
@section('title', 'This field is empty')
@section('message', "We couldn't find the page you're looking for. It may have been moved, harvested, or the link was mistyped.")
