@extends('errors.layout')
@section('code', '419')
@section('emoji', '⏳')
@section('title', 'Your session expired')
@section('message', 'For your safety, this page was left open too long. Go back and sign in again. Nothing was lost.')
