@extends('errors.layout')
@section('code', '429')
@section('emoji', '🐢')
@section('title', 'Slow down a little')
@section('message', "Too many tries in a short time. Please wait a few seconds and try again.")
