@extends('errors.layout')
@section('code', '500')
@section('emoji', '🚜')
@section('title', 'Something broke on our end')
@section('message', "This is not your fault. Our team has been told. Please try again in a moment.")
