@extends('errors.layout')
@section('code', '500')
@section('emoji', '🚜')
@section('title', 'Something broke on our end')
@section('message', "A gear slipped in the machine — this isn't your fault. Our team has been notified. Please try again in a moment.")
