@extends('errors.layout')
@section('code', '503')
@section('emoji', '🌧️')
@section('title', 'Back in a few minutes')
@section('message', "We are fixing and improving the app. This usually takes only a few minutes. Please check back soon.")
