"""Where each keyword from anisenso_keywords.csv lives: its primary page first,
then the pages that also use it naturally. Writes keywords.json.

    python database/site-pages/keyword_map.py
"""
import csv
import json
import os

HERE = os.path.dirname(os.path.abspath(__file__))

P = {
    'palay': 'crops/palay', 'pnp': 'crops/pagtatanim-ng-palay', 'var': 'crops/rice-varieties-philippines',
    'kernel': 'crops/corn-kernel', 'cseeds': 'crops/corn-seeds', 'pnm': 'crops/pagtatanim-ng-mais',
    'maisrice': 'crops/mais-rice', 'veg': 'crops/vegetables-philippines', 'png': 'crops/pagtatanim-ng-gulay',
    'coco': 'crops/coconut-fertilizer', 'banana': 'crops/banana-farming-philippines', 'puno': 'crops/pagtatanim-ng-puno',
    'ricebug': 'pests/rice-bug', 'blackbug': 'pests/rice-black-bug', 'bph': 'pests/brown-planthopper',
    'riceins': 'pests/rice-insects', 'lf': 'pests/rice-leaffolder', 'thrips': 'pests/thrips',
    'faw': 'pests/fall-armyworm', 'acb': 'pests/asian-corn-borer', 'cutworm': 'pests/cutworm',
    'anth': 'diseases/anthracnose', 'fus': 'diseases/fusarium-wilt', 'sb': 'diseases/sheath-blight',
    'weeds': 'weeds/common-weeds-philippines', 'hanip': 'pests/hanip-mites-and-aphids',
    'urea': 'blog/urea-fertilizer', 'complete': 'blog/complete-fertilizer-14-14-14', 'p1620': 'blog/16-20-0-fertilizer',
    'as': 'blog/ammonium-sulfate-21-0-0', 'potash': 'blog/potash-fertilizer', 'foliar': 'blog/foliar-fertilizer',
    'organic': 'blog/organic-fertilizer-examples', 'inorg': 'blog/inorganic-fertilizer-examples',
    'calc': 'blog/fertilizer-calculation', 'apply': 'blog/fertilizer-application-methods', 'frice': 'blog/fertilizer-for-rice',
    'fplants': 'blog/fertilizer-for-plants', 'brands': 'blog/fertilizer-brands-and-dealers',
    'fpa': 'blog/fertilizer-and-pesticide-authority', 'riceinsect': 'blog/rice-insecticides-alika-virtako-chess',
    'karate': 'blog/karate-cymbush-selecron-insecticides', 'fungi': 'blog/fungicides', 'ant': 'blog/ant-bait-and-termiticides',
    'alamat': 'blog/alamat-ng-palay', 'alamatmais': 'blog/alamat-ng-mais', 'words': 'blog/farm-words-in-tagalog',
    'price': 'blog/palay-price-philippines', 'palayan': 'blog/palayan-nueva-ecija', 'ani': 'blog/ani-meaning',
    'econ': 'blog/agriculture-in-the-philippine-economy', 'career': 'blog/agricultural-engineer-career',
    'ai': 'features/ai-agricultural-technician', 'reports': 'features/farm-reports',
}

# keyword -> page keys, primary first
MAP = {
    'palay': ['palay', 'pnp', 'price', 'var'],
    'palayan nueva ecija': ['palayan', 'palay'],
    'ani': ['ani', 'pnp', 'reports'],
    'corn kernel': ['kernel', 'maisrice', 'cseeds'],
    'corn flakes': ['kernel', 'maisrice'],
    'alamat ng palay': ['alamat', 'alamatmais', 'palay'],
    'palayan': ['palayan', 'palay', 'words'],
    'palay in english': ['palay', 'words'],
    'palaya natural farm': ['organic', 'veg'],
    'fertilizer urea': ['urea', 'frice', 'calc'],
    'corn husk': ['kernel', 'pnm'],
    'fertilizer plants': ['fplants', 'organic'],
    'weeds in tagalog': ['words', 'weeds'],
    'thrips insect': ['thrips', 'riceins'],
    'pagtatanim': ['pnp', 'png', 'puno'],
    'diseased in tagalog': ['words', 'anth'],
    'thrips': ['thrips', 'veg', 'hanip'],
    'foliar fertilizer': ['foliar', 'apply', 'veg'],
    'alitangya': ['ricebug', 'words'],
    'pagtatanim ng puno': ['puno', 'coco'],
    'corn scientific name': ['kernel', 'cseeds'],
    'fertilizer pesticide authority': ['fpa', 'brands'],
    'fertilizer and pesticide authority': ['fpa', 'riceinsect', 'karate'],
    'bugs in tagalog': ['words', 'ricebug'],
    'fertilizer 14 14 14': ['complete', 'frice', 'veg'],
    'fertilizer dealer supply': ['brands', 'fpa'],
    '14 14 14 fertilizer': ['complete', 'calc'],
    'rice seed': ['palay', 'var', 'pnp'],
    'rice seeds': ['var', 'palay'],
    'rice bug': ['ricebug', 'riceins', 'blackbug'],
    'rice palay price philippines': ['price', 'palay'],
    'seeds rice': ['palay', 'var'],
    'rice bugs': ['ricebug', 'riceins'],
    '16 20 0 fertilizer': ['p1620', 'frice', 'calc'],
    'corn seeds': ['cseeds', 'pnm', 'kernel'],
    'fungicide': ['fungi', 'anth', 'sb', 'fus'],
    'corn seedling': ['cseeds', 'cutworm'],
    'fertilizer complete': ['complete', 'inorg'],
    'complete fertilizer': ['complete', 'apply', 'png'],
    'mite in tagalog': ['words', 'hanip'],
    'agriculture in economy': ['econ', 'ani'],
    'ant bait': ['ant', 'karate'],
    'maggots in tagalog': ['words', 'organic'],
    'mites in tagalog': ['words', 'hanip'],
    '21 0 0 fertilizer': ['as', 'frice', 'urea'],
    'palayan drawing': ['palayan', 'palay'],
    'anthracnose': ['anth', 'fungi', 'veg'],
    'corns in tagalog': ['words', 'kernel'],
    'palayan in english': ['palayan', 'words'],
    'vegetables in the philippines': ['veg', 'png'],
    'fall armyworm': ['faw', 'acb', 'pnm'],
    'ammonium sulfate fertilizer': ['as', 'inorg'],
    'cutworm': ['cutworm', 'png'],
    'mais rice': ['maisrice', 'kernel'],
    'syngenta philippines': ['riceinsect', 'fungi'],
    'fertilizer yara': ['brands', 'complete'],
    'atlas fertilizer': ['brands', 'p1620'],
    'alika insecticide': ['riceinsect', 'ricebug'],
    'rice black bug': ['blackbug', 'riceins'],
    'pagtatanim ng palay': ['pnp', 'palay', 'alamat'],
    'rice variety philippines': ['var', 'palay'],
    'virtako insecticide': ['riceinsect', 'lf'],
    'urea fertilizer price': ['urea', 'brands'],
    'philippine rice variety': ['var', 'palayan'],
    'palay image': ['palay', 'alamat'],
    'potash fertilizer': ['potash', 'banana', 'coco'],
    'fusarium wilt': ['fus', 'banana'],
    'variety of rice in the philippines': ['var', 'pnp'],
    'examples of organic fertilizer': ['organic', 'fplants'],
    'example of organic fertilizer': ['organic', 'png'],
    'philippine rice variety list': ['var', 'palay'],
    'fertilizer 21 0 0': ['as', 'apply'],
    'broadleaves': ['weeds', 'pnp'],
    'philippines insects': ['riceins', 'thrips'],
    'palay picture': ['palay', 'price'],
    'triple 14 fertilizer': ['complete', 'veg'],
    'planthopper': ['bph', 'riceins'],
    'plant hopper': ['bph', 'riceinsect'],
    'cymbush insecticide': ['karate', 'cutworm'],
    'broadleaves weeds': ['weeds', 'pnm'],
    'rice varieties philippines': ['var', 'price'],
    'karate insecticide': ['karate', 'ricebug'],
    'rice variety in the philippines': ['var', 'palay'],
    'brown planthopper': ['bph', 'riceinsect', 'riceins'],
    'brown plant hopper symptoms': ['bph', 'riceins'],
    'grass in tagalog': ['words', 'weeds'],
    'sedges weeds': ['weeds', 'pnp'],
    'kinds of rice in the philippines': ['var', 'maisrice'],
    'gulay na mais': ['kernel', 'pnm'],
    'best fertilizer for vegetables': ['veg', 'fplants', 'organic'],
    'rice variety': ['var', 'pnp'],
    'sedge weed': ['weeds', 'palay'],
    'rice black bugs': ['blackbug', 'riceins'],
    'fertilizer nitrogen': ['urea', 'as'],
    'black rice bug': ['blackbug', 'words'],
    'natural fertilizer for plants': ['organic', 'puno'],
    'nitrogen fertilizer': ['urea', 'frice'],
    'rice variety rice': ['var', 'palay'],
    'insecticide karate': ['karate', 'faw'],
    'hanip insect': ['hanip', 'words'],
    'asian corn borer': ['acb', 'pnm', 'faw'],
    'fertilizer urea price': ['urea', 'calc'],
    'asiatic corn borer': ['acb', 'kernel'],
    'fertilizer with potassium': ['potash', 'coco'],
    'palay price today': ['price', 'palay'],
    'eggshell as fertilizer': ['organic', 'png'],
    'fertilizer with phosphorus': ['p1620', 'fplants'],
    'fertilizer 46 0 0': ['urea', 'calc'],
    'fertilizer liquid': ['foliar', 'fplants'],
    'fertilizer chemical': ['inorg', 'fpa'],
    'rice insect': ['riceins', 'lf'],
    'foliar fertilizer spray': ['foliar', 'veg'],
    'liquid fertilizer': ['foliar', 'organic'],
    'jasponica rice': ['var', 'price'],
    'corn kernel price': ['kernel', 'pnm'],
    'egg shell fertilizer': ['organic', 'fplants'],
    'fertilizer for coconut plants': ['coco', 'potash'],
    'rice insects': ['riceins', 'ricebug'],
    'fertilizer for coconut tree': ['coco', 'puno'],
    'fertilizer application': ['apply', 'frice', 'calc'],
    'fertilizer calculation': ['calc', 'frice', 'urea'],
    '46 0 0 fertilizer': ['urea', 'complete'],
    'selecron insecticide': ['karate', 'thrips'],
    'armure fungicide': ['fungi', 'sb'],
    'yara winner fertilizer': ['brands', 'complete'],
    'fertilizer for tomato plants': ['veg', 'foliar'],
    'fertilizer drawing': ['apply', 'inorg'],
    'maisan': ['pnm', 'kernel'],
    'osmocote fertilizer': ['fplants', 'inorg'],
    'common weeds in the philippines': ['weeds', 'pnp'],
    'ortiva top fungicide': ['fungi', 'anth'],
    'fertilizer for coconut': ['coco', 'banana'],
    'corn bran': ['kernel', 'maisrice'],
    'chicken dung as fertilizer': ['organic', 'veg'],
    'seeds corn': ['cseeds', 'pnm'],
    'cymbush': ['karate', 'faw'],
    'complete fertilizer 14 14 14': ['complete', 'png'],
    'variety of corn': ['cseeds', 'kernel'],
    'synthetic fertilizer': ['inorg', 'organic'],
    'fertilizer applicator': ['apply', 'frice'],
    'sl agritech corporation': ['var', 'price'],
    'alibangbang insect': ['riceins', 'words'],
    'mildew in tagalog': ['words', 'fungi'],
    'chess insecticide': ['riceinsect', 'bph'],
    'agricultural technician': ['ai', 'career'],
    'fertilizer spreader': ['apply', 'frice'],
    'tayangaw': ['ricebug', 'words'],
    'pagtatanim ng halaman': ['puno', 'png'],
    'palatak palay seeder': ['pnp', 'palay'],
    'telluride insecticide': ['karate', 'riceinsect'],
    'agricultural equipment technician': ['career', 'ai'],
    'alamat ng palay buod': ['alamat'],
    'agricultural engineer hiring': ['career', 'econ'],
    'aphids scientific name': ['hanip', 'veg'],
    'rice leaffolder': ['lf', 'riceins'],
    'rice brands in the philippines': ['var', 'price'],
    'fertilizer in tagalog': ['words', 'urea'],
    'lambda cyhalothrin': ['karate', 'ricebug'],
    'agricultural engineer course': ['career'],
    'banghay ng alamat ng palay': ['alamat'],
    'fertilizer for flowering plants': ['fplants', 'potash'],
    'ammonia nitrate fertilizer': ['as', 'inorg'],
    'banana farming philippines': ['banana', 'fus'],
    'top dressing fertilizer': ['apply', 'urea'],
    'pagtatanim ng gulay': ['png', 'veg'],
    'biostimulants': ['foliar', 'organic'],
    'termiticides': ['ant', 'karate'],
    'fertilizer computation': ['calc', 'frice'],
    'sofit': ['weeds', 'pnp'],
    'example of inorganic fertilizer': ['inorg', 'organic'],
    'examples of inorganic fertilizer': ['inorg', 'fplants'],
    'pesticide in tagalog': ['words', 'fpa'],
    'agricultural engineer pay': ['career'],
    'treser ng palay': ['pnp', 'palay'],
    'cavan rice': ['price', 'palay'],
    'black bug insect': ['blackbug', 'riceins'],
    'fertilizer for plants and flowers': ['fplants', 'organic'],
    'fertilizer for top dressing': ['apply', 'frice'],
    'pest in tagalog': ['words', 'riceins'],
    'fish amino acid fertilizer': ['organic', 'png'],
    'grasses weeds': ['weeds', 'pnm'],
    'palay price per kilo today': ['price', 'palay'],
    'foliar application fertilizer': ['foliar', 'apply'],
    'organic fertilizer benefits': ['organic', 'fplants'],
    'rice hybrid': ['var', 'palay'],
    'fertilizer example': ['inorg', 'fplants'],
    'fertilizer picture': ['apply', 'complete'],
    'fertilizer for vegetables': ['veg', 'png'],
    'method of fertilizer application': ['apply', 'frice'],
    'english ng palay': ['palay', 'words'],
    '16 20 fertilizer': ['p1620', 'veg'],
    'rice variety 216': ['var', 'pnp'],
    'fertilizer eggs': ['organic'],
    'rice ear bug': ['ricebug', 'riceins'],
    'sheath blight disease': ['sb', 'fungi'],
    'palay festival': ['alamat', 'palay'],
    'sheath blight': ['sb', 'fungi', 'riceins'],
    'humus fertilizer': ['organic', 'puno'],
    'fertilizer 16 16 16': ['complete', 'veg'],
    'fertilizer in agriculture': ['fplants', 'econ'],
    'fertilizer 20 20 20': ['complete', 'foliar'],
    'commercial fertilizer': ['inorg', 'brands'],
    'fertilizer for rice': ['frice', 'pnp', 'urea'],
    'fish emulsion fertilizer': ['organic', 'foliar'],
    'fertilizer granules': ['inorg', 'apply'],
    'fertilizer application methods': ['apply', 'png'],
    'palay check system': ['pnp', 'frice'],
    'palay rice': ['palay', 'price'],
    'fertilizer calculation formula': ['calc'],
    'fertilizer examples': ['inorg', 'organic'],
    'palay to rice': ['palay', 'price'],
    'pag aani ng palay': ['pnp', 'palay'],
    'palay meaning': ['palay', 'ani'],
    'mais na gulay': ['kernel', 'png'],
    'mais rice benefits': ['maisrice'],
    'jackpot rice variety maturity': ['var'],
    'palay seedlings': ['pnp', 'palay'],
    'pagtatanim ng mais': ['pnm', 'kernel'],
    'corn seed grow a garden roblox': ['cseeds'],
    'palay seeds': ['palay', 'var'],
    'fertilizer high in phosphorus': ['p1620', 'fplants'],
    'when fertilization occurs': ['kernel', 'cseeds'],
    'fertilizer names list': ['inorg', 'fplants'],
    '402 rice variety characteristics': ['var'],
    'alamat ng mais': ['alamatmais', 'alamat'],
    'rice variety 222': ['var'],
    'crop yields meaning': ['ani', 'reports'],
    'fertilizer for coconut tree in philippines': ['coco'],
    'rice breed': ['var'],
    'fertilizer with high potassium': ['potash', 'banana'],
    'why fertilizer is important': ['fplants', 'frice'],
    'what fertilizer for plants': ['fplants'],
    'corn breed': ['cseeds', 'kernel'],
}


def main():
    rows = list(csv.DictReader(open(os.path.join(os.path.expanduser('~'), 'Downloads', 'anisenso_keywords.csv'), encoding='utf-8-sig')))
    vol = {}
    for r in rows:
        k = r['Keyword'].strip().lower()
        vol[k] = max(vol.get(k, 0), int(r['Volume'] or 0))
    missing = [k for k in vol if k not in MAP]
    extra = [k for k in MAP if k not in vol]
    if missing or extra:
        raise SystemExit('unmapped: %s | not in csv: %s' % (missing, extra))
    out = {k: {'volume': vol[k], 'pages': [P[p] for p in MAP[k]]} for k in sorted(vol, key=lambda k: -vol[k])}
    json.dump(out, open(os.path.join(HERE, 'keywords.json'), 'w', encoding='utf-8'), indent=1)
    by_page = {}
    for k, v in out.items():
        for i, p in enumerate(v['pages']):
            by_page.setdefault(p, []).append(('*' if i == 0 else '') + k)
    json.dump(by_page, open(os.path.join(HERE, 'keywords_by_page.json'), 'w', encoding='utf-8'), indent=1)
    print('%d keywords over %d pages' % (len(out), len(by_page)))


if __name__ == '__main__':
    main()
