<?php

namespace App\Support;

/**
 * GENERATED by the scratchpad's npk/make_crops.py from the research table of
 * 2026-10-07; change the table and run it again rather than editing here.
 *
 * What each crop takes up per ton of harvest (N, P2O5, K2O, kg), its usual
 * Philippine yield (FAOSTAT national averages 2018 to 2024, which carry the
 * PSA's figures), the recommended rates per hectare from DA, PhilRice and
 * state university guides (a tree crop's rate per tree counted at
 * treesPerHa), and the recovery the crop's own source assumed. A legume
 * fixes most of its own nitrogen; removalOnly marks a figure that counts
 * only what the harvest carries away, not what the plant needs to grow.
 * NPK Plus shows all of it as a general guide, with its sources.
 */
final class NpkCrops
{
    public const TABLE = [
        'rice' => [
            'uptakePerTon' => ['N' => 22.2, 'P2O5' => 7.1, 'K2O' => 31.6],
            'recommendedPerHa' => ['N' => [97, 139], 'P2O5' => [64.2, 80.2], 'K2O' => [51.8, 60.2]],
            'efficiency' => ['N' => 0.4, 'P2O5' => 0.2, 'K2O' => 0.35],
            'typicalYield' => ['lo' => 3.97, 'hi' => 4.17, 'unit' => 't/ha palay'],
            'about' => 'Uptake: total above-ground uptake, grain plus straw (IR36, Laguna, Philippines). Rate: PhilRice modified general recommendation for irrigated lowland (fixed-rate fixed-time): wet season N 97, P 28, K 43; dry season N 139, P 35, K 50 kg/ha. The table is headed \'Nutrient Element\' so P and K were converted to P2O5 (x2.291) and K2O (x1.205). Yield: FAOSTAT item \'Rice\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual, Rice chapter (De Datta 1989, IR36 in the Philippines)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'PhilRice, Reinforcing right E-A-T for improved fertilizer application (Table 1, modified general recommendation)',
                    'url' => 'https://www.philrice.gov.ph/reinforcing-right-e-a-t-for-improved-fertilizer-application',
                ],
                [
                    'label' => 'Sta. Cruz (UPLB), Nutrient management in improving the productivity of lowland rice in the Philippines, SEARCA 2011 slides',
                    'url' => 'https://www.searca.org/~searca/phocadownload/ADSS_2011/adss-Nutrient%20Management%20in%20Improving%20the%20Productivity%20of%20Lowland%20Rice%20in%20the%20Philippines-2011-jun-28.pdf',
                ],
            ],
        ],
        'corn_yellow' => [
            'uptakePerTon' => ['N' => 20.61, 'P2O5' => 8.88, 'K2O' => 18.57],
            'recommendedPerHa' => ['N' => [130, 151], 'P2O5' => [30, 110], 'K2O' => [30, 95]],
            'typicalYield' => ['lo' => 3.09, 'hi' => 3.31, 'unit' => 't/ha grain (all maize types)'],
            'about' => 'Uptake: total uptake, grain plus stover, measured on corn yielding 9.8 t/ha in Cagayan, Isabela, Bukidnon and Misamis Oriental (UPLB); P, K, Ca, Mg converted from elemental form. Rate: Range of Philippine results: DK 9051 at Bagumbayan, Sultan Kudarat 130-30-30 (6.76 t/ha, Region 12 study); Enrile, Cagayan site-specific 145-110-67; IRRI SSNM average recommendation 151-83-95 (Indonesia, Philippines, Vietnam). Farmers\' practice in the same SSNM trials was 167-71-77. Yield: FAOSTAT item \'Maize (corn)\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'Samonte et al. (UPLB), Soil fertility improvement for sustained high corn yields in major corn growing provinces in the Philippines, ASA-CSSA-SSSA 2011 abstract',
                    'url' => 'https://scisoc.confex.com/crops/2011am/webprogram/Paper66712.html',
                ],
                [
                    'label' => 'Pampolino (IPNI/IRRI), Site-specific nutrient management for tropical maize, IFA Crossroads 2009 slides',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/2023/01/2009_crossroads_pampolino_slides.pdf',
                ],
                [
                    'label' => 'AGRIS, Multi-location nutrient management studies on corn in Region 12 (Central Mindanao)',
                    'url' => 'https://agris.fao.org/search/fr/records/64724af9e17b74d2224fa102',
                ],
            ],
        ],
        'corn_sweet' => [
            'uptakePerTon' => ['N' => 10.4, 'P2O5' => 3, 'K2O' => 11.4],
            'about' => 'Uptake: total plant uptake for 20 t/ha fresh weight (IFA, Fox 1973 and others; Hawaii based); derived by dividing the per-hectare figures (N 208, P2O5 60, K2O 228, MgO 25, CaO 42, S 14 kg and Zn 0.21 kg per ha) by 20.',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual, Sweet Corn chapter',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'sorghum' => [
            'uptakePerTon' => ['N' => 22, 'P2O5' => 13, 'K2O' => 34],
            'typicalYield' => ['lo' => 4.85, 'hi' => 6.27, 'unit' => 't/ha grain'],
            'about' => 'Uptake: total uptake (IPNI Table 4.1, India). Yield: FAOSTAT item \'Sorghum\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IPNI / Plant Nutrition Canada, 4R Plant Nutrition Manual, Table 4.1 total nutrient uptake and Table 4.5 nutrient removal (metric)',
                    'url' => 'https://plantnutrition.ca/wp-content/uploads/2022/12/Metric-4_1-4_5-0115.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'mungbean' => [
            'uptakePerTon' => ['N' => 131.29, 'P2O5' => 18.29, 'K2O' => 119.43],
            'recommendedPerHa' => ['N' => [21, 28], 'P2O5' => [21, 28], 'K2O' => [21, 28]],
            'typicalYield' => ['lo' => 0.85, 'hi' => 0.9, 'unit' => 't/ha dry beans'],
            'legume' => true,
            'about' => 'Uptake: total plant uptake of 91.9 N, 12.8 P2O5, 83.6 K2O kg/ha at 0.7 t/ha grain (IFA, Kothari 1984, India); divided by 0.7. Rate: DA: without soil analysis, 3 bags (150 kg) of 14-14-14 per ha on heavy soils, 4 bags (200 kg) on light soils, dry season, basal. Guide also says to apply about 30 to 45 kg per ha each of P and K on P- and K-deficient soils. Mungbean fixes its own N. Yield: FAOSTAT item \'Beans, dry\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA HVCDP Mungbean Production Guide',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Mungbean-Production-Guide.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'peanut' => [
            'uptakePerTon' => ['N' => 63.5, 'P2O5' => 14, 'K2O' => 31.83],
            'typicalYield' => ['lo' => 1.12, 'hi' => 1.33, 'unit' => 't/ha in-shell pods'],
            'legume' => true,
            'about' => 'Uptake: total plant uptake (pods plus vines); mean of IFA USA (3 t/ha pods: N 192, P2O5 48, K2O 80, CaO 79 kg/ha) and IPNI Table 4.1 India (N 63, P2O5 12, K2O 37). Yield: FAOSTAT item \'Groundnuts, excluding shelled\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'IPNI / Plant Nutrition Canada, 4R Plant Nutrition Manual, Table 4.1 total nutrient uptake and Table 4.5 nutrient removal (metric)',
                    'url' => 'https://plantnutrition.ca/wp-content/uploads/2022/12/Metric-4_1-4_5-0115.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'soybean' => [
            'uptakePerTon' => ['N' => 80, 'P2O5' => 15.33, 'K2O' => 36.67],
            'recommendedPerHa' => ['N' => [14, 14], 'P2O5' => [14, 14], 'K2O' => [14, 14]],
            'typicalYield' => ['lo' => 1.34, 'hi' => 1.81, 'unit' => 't/ha grain'],
            'legume' => true,
            'about' => 'Uptake: total uptake including stover; mean of two IFA \'total\' rows (N 81/77, P2O5 14/14, K2O 33/39) and IPNI Table 4.1 USA (N 82, P2O5 18, K2O 38). Rate: DA RFO 02 Soybean Production Guide: without soil analysis apply 2 bags of 14-14-14 per ha basal (2 x 50 kg x 14 percent = 14 kg each of N, P2O5, K2O). Inoculate the seed. Yield: FAOSTAT item \'Soya beans\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Soybean Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/soybean281111.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'IPNI / Plant Nutrition Canada, 4R Plant Nutrition Manual, Table 4.1 total nutrient uptake and Table 4.5 nutrient removal (metric)',
                    'url' => 'https://plantnutrition.ca/wp-content/uploads/2022/12/Metric-4_1-4_5-0115.pdf',
                ],
            ],
        ],
        'stringbean' => [
            'uptakePerTon' => ['N' => 9.92, 'P2O5' => 1.62, 'K2O' => 5.23],
            'recommendedPerHa' => ['N' => [28, 28], 'P2O5' => [28, 28], 'K2O' => [28, 28]],
            'typicalYield' => ['lo' => 7.78, 'hi' => 8.22, 'unit' => 't/ha fresh pods'],
            'legume' => true,
            'proxy' => 'French/snap bean used as the nearest vegetable bean in IFA; sitao (yardlong bean) is Vigna unguiculata ssp. sesquipedalis',
            'about' => 'Uptake: total plant uptake at 13 t/ha (129 N, 21 P2O5, 68 K2O, 17 MgO, 50 CaO kg/ha) from IFA \'Beans\' (French bean, Phaseolus vulgaris); divided by 13. Rate: DA RFO V Bicol sitao guide: without soil analysis 4 bags of 14-14-14 plus 10 bags organic fertilizer per ha at planting (4 x 50 kg x 14 percent). Snap beans in the same guide: N 30 to 50, P 70 to 120, K 30 to 50 kg/ha. Yield: FAOSTAT item \'String beans\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'sweetpotato' => [
            'uptakePerTon' => ['N' => 3.93, 'P2O5' => 1.05, 'K2O' => 5.81],
            'recommendedPerHa' => ['N' => [42, 120], 'P2O5' => [38, 56], 'K2O' => [42, 90]],
            'typicalYield' => ['lo' => 5.77, 'hi' => 6.74, 'unit' => 't/ha fresh roots'],
            'about' => 'Uptake: total uptake, leaves plus roots; mean of IFA rows Wenkam 1983 (14 t/ha: N 51.6, P2O5 17.2, K2O 71.0) and Tsuno 1972 (20 t/ha: N 83.6, P2O5 17.4, K2O 130.8); MgO and CaO from the first row only. Rate: DA RFO 02: without soil analysis 6 to 8 sacks of 14-14-14 per ha (42 to 56 kg each of N, P2O5, K2O), all at planting or split. VSU/Leyte trial (Asio et al. 2018): optimum 118-38-90 on a high-P, high-K soil; the paper cites about 120 kg N/ha as the Philippine recommendation and used a 40-40-60 reference rate. Yield: FAOSTAT item \'Sweet potatoes\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Sweet Potato Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/sweet_potato.pdf',
                ],
                [
                    'label' => 'Asio et al., Response of a traditional sweetpotato variety to fertilization in Leyte, Philippines (Tropentag 2018)',
                    'url' => 'https://www.tropentag.de/2018/abstracts/full/621.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'cassava' => [
            'uptakePerTon' => ['N' => 5.04, 'P2O5' => 1.6, 'K2O' => 5.95],
            'recommendedPerHa' => ['N' => [56, 180], 'P2O5' => [56, 70], 'K2O' => [56, 250]],
            'typicalYield' => ['lo' => 10.05, 'hi' => 11.96, 'unit' => 't/ha fresh roots'],
            'about' => 'Uptake: whole-plant uptake (roots plus stems and leaves); mean of three IFA rows at 18, 37 and 45 t/ha (Sittibusaya, Howeler 1985, Amarasiri 1975), each divided by its yield. Rate: National fertilizer recommendation 8 bags of 14-14-14 per ha (8 x 50 kg x 14 percent = 56-56-56; DA RFO 03: 4 bags basal plus 4 bags two months after planting). SSNM/4R prototype 180-70-250 gave 21 percent more root yield than the national rate in Philippine trials. Yield: FAOSTAT item \'Cassava, fresh\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'AGRIS, Towards increasing cassava production in the Philippines through site-specific nutrient management',
                    'url' => 'https://agris.fao.org/search/fr/records/6473b0c413d110e4e7a990e6',
                ],
                [
                    'label' => 'DA RFO 03 Cassava leaflet',
                    'url' => 'https://rfo3.da.gov.ph/wp-content/uploads/elibrary/km/Cassava.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'taro' => [
            'uptakePerTon' => ['N' => 6.07, 'P2O5' => 2.03, 'K2O' => 8.28],
            'typicalYield' => ['lo' => 6.21, 'hi' => 7.58, 'unit' => 't/ha fresh corms'],
            'about' => 'Uptake: whole-plant uptake (IFA, Colocasia esculenta, Kabeerathumma et al. 1987 at 17 t/ha and Mohankumar 1986 at 12.3 t/ha, India), mean of the two; MgO, CaO and S from the first row. Yield: FAOSTAT item \'Taro\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'potato' => [
            'uptakePerTon' => ['N' => 4.95, 'P2O5' => 1.47, 'K2O' => 9.33],
            'recommendedPerHa' => ['N' => [120, 140], 'P2O5' => [140, 240], 'K2O' => [140, 240]],
            'typicalYield' => ['lo' => 15.45, 'hi' => 16.22, 'unit' => 't/ha tubers'],
            'about' => 'Uptake: total uptake including tops; mean of IPNI Table 4.1 Australia (N 4.9, P2O5 2.1, K2O 12) and IFA Wirsing 1990 whole plant at 30 t/ha (N 150, P2O5 25, K2O 200, MgO 20, CaO 60 kg/ha). Rate: DA RFO 02 White Potato guide: general recommendation 120 N, 240 P2O5, 240 K2O per ha (3 bags 14-14-14 basal, remaining N and K at hilling up, plus 20 bags organic). Benguet State University: 140-140-140 plus 5 t/ha organic fertilizer and boron gave the heaviest marketable yield. Yield: FAOSTAT item \'Potatoes\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley White Potato Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/White-Potato-Production-Guide.pdf',
                ],
                [
                    'label' => 'Benguet State University, Balanced Fertilization Strategy for semi-temperate vegetables in the highlands (abstract)',
                    'url' => 'https://journals.bsu.edu.ph/mjsir/article/view/225',
                ],
                [
                    'label' => 'IPNI / Plant Nutrition Canada, 4R Plant Nutrition Manual, Table 4.1 total nutrient uptake and Table 4.5 nutrient removal (metric)',
                    'url' => 'https://plantnutrition.ca/wp-content/uploads/2022/12/Metric-4_1-4_5-0115.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'carrot' => [
            'uptakePerTon' => ['N' => 2.93, 'P2O5' => 1.65, 'K2O' => 4.07],
            'recommendedPerHa' => ['N' => [90, 132], 'P2O5' => [63, 170], 'K2O' => [63, 90]],
            'typicalYield' => ['lo' => 12.22, 'hi' => 13.74, 'unit' => 't/ha roots'],
            'about' => 'Uptake: total uptake at 43 t/ha (N 126, P2O5 71, K2O 175, MgO 20 kg/ha; IFA \'various sources\', India); divided by 43. The CaO figure in that table (224 kg/ha) looks too high and is left out. Rate: Benguet State University: 90-170-90 plus boron gave the heaviest yield. DA RFO V Bicol: 6 bags 14-14-14 basal plus 3 bags 14-14-14 and 3 bags urea as side dressing (63-63-63 from complete fertilizer plus 69 N from urea = 132-63-63), plus 20 bags compost. Yield: FAOSTAT item \'Carrots and turnips\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'Benguet State University, Balanced Fertilization Strategy for semi-temperate vegetables in the highlands (abstract)',
                    'url' => 'https://journals.bsu.edu.ph/mjsir/article/view/225',
                ],
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'ginger' => [
            'recommendedPerHa' => ['N' => [180, 250], 'P2O5' => [100, 180], 'K2O' => [100, 255]],
            'typicalYield' => ['lo' => 5.38, 'hi' => 7.11, 'unit' => 't/ha fresh rhizome'],
            'about' => 'Rate: DA-CAR technoguide: general requirement 180 kg N, 180 kg P2O5, 255 kg K2O per ha. DA RFO V Bicol: general recommendation 250-100-100 kg, all P and K and part of the N at land preparation, rest of the N at 60, 90 and 120 days. Yield: FAOSTAT item \'Ginger, raw\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA-CAR Technoguide in Production and Management of Ginger (DA HVCDP)',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/DA-CAR-TECHNOGUIDE-IN-PRODUCTION-_-MANAGEMENT-OF-GINGER.pdf',
                ],
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'pechay' => [
            'recommendedPerHa' => ['N' => [85, 85], 'P2O5' => [20, 20]],
            'about' => 'Rate: DA RFO V Bicol pechay and mustard: before transplanting 2 bags 16-20-0 and 2 bags 46-0-0 per ha, plus 1 bag 46-0-0 a few days after transplanting (N 16+46+23 = 85, P2O5 20), with 5 to 10 t/ha organic fertilizer. Grade arithmetic is mine, from 50 kg bags.',
            'sources' => [
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
            ],
        ],
        'cabbage' => [
            'uptakePerTon' => ['N' => 4.17, 'P2O5' => 1.1, 'K2O' => 3.66],
            'recommendedPerHa' => ['N' => [90, 250], 'P2O5' => [21, 100], 'K2O' => [21, 111]],
            'typicalYield' => ['lo' => 15.21, 'hi' => 16.32, 'unit' => 't/ha heads'],
            'about' => 'Uptake: total uptake at 29 t/ha (N 121, P2O5 32, K2O 106, MgO 5, CaO 21 kg/ha; IFA \'various sources\'); divided by 29. Rate: DA RFO 02: 3 bags 14-14-14 at 3 to 5 days after transplanting plus 3 bags urea at 30 days (N 21+69 = 90, P2O5 21, K2O 21; the cost sheet adds 3 bags 0-0-60, giving K2O 111). Benguet State University farmers\' rate and best trial rate 250-100-100 plus 7 t/ha chicken manure. Yield: FAOSTAT item \'Cabbages\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Cabbage Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Cabbage.pdf',
                ],
                [
                    'label' => 'Benguet State University, Balanced Fertilization Strategy for semi-temperate vegetables in the highlands (abstract)',
                    'url' => 'https://journals.bsu.edu.ph/mjsir/article/view/225',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'lettuce' => [
            'uptakePerTon' => ['N' => 3.78, 'P2O5' => 1.17, 'K2O' => 7.22],
            'recommendedPerHa' => ['N' => [83, 83], 'P2O5' => [14, 14], 'K2O' => [74, 74]],
            'typicalYield' => ['lo' => 4.57, 'hi' => 8.82, 'unit' => 't/ha'],
            'about' => 'Uptake: total uptake at 18 t/ha (N 68, P2O5 21, K2O 130, MgO 8, CaO 20 kg/ha; IFA \'various sources\'); divided by 18. Rate: DA RFO 02 lettuce cost sheet: 2 bags 14-14-14, 3 bags 46-0-0 and 2 bags 0-0-60 per ha (per hill: 10 g 14-14-14 basal, then 5 g of a 1:1 urea and potash mix at 15 and 30 days). Yield: FAOSTAT item \'Lettuce and chicory\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Lettuce Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Lettuce.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'broccoli' => [
            'uptakePerTon' => ['N' => 5.35, 'P2O5' => 1.78, 'K2O' => 7.97],
            'recommendedPerHa' => ['N' => [180, 240], 'P2O5' => [45, 60], 'K2O' => [45, 60]],
            'typicalYield' => ['lo' => 10.16, 'hi' => 11.89, 'unit' => 't/ha'],
            'proxy' => 'cauliflower (Brassica oleracea var. botrytis), the closest crop in the IFA manual; no broccoli uptake table was opened',
            'about' => 'Uptake: total uptake at 37 t/ha (N 198, P2O5 66, K2O 295, MgO 21, CaO 186 kg/ha; IFA, Anstett 1961) for CAULIFLOWER; divided by 37. Rate: Benguet State University: 240-60-60 plus 5 t/ha compost and boron gave the heaviest yield and biggest curds; cutting the recommended rate by 25 percent with chicken manure and boron gave comparable yields (the low end here is that 75 percent). Yield: FAOSTAT item \'Cauliflowers and broccoli\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'Benguet State University, Balanced Fertilization Strategy for semi-temperate vegetables in the highlands (abstract)',
                    'url' => 'https://journals.bsu.edu.ph/mjsir/article/view/225',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'tomato' => [
            'uptakePerTon' => ['N' => 2.8, 'P2O5' => 1.3, 'K2O' => 3.8],
            'recommendedPerHa' => ['N' => [116, 165], 'P2O5' => [40, 95], 'K2O' => [120, 215]],
            'typicalYield' => ['lo' => 13.39, 'hi' => 14.97, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: total plant uptake. N, P2O5, K2O from IPNI Table 4.1 (India). CaO, MgO and S from Yara (US) per short ton of fruit: Ca 3.4 lb/t, Mg 0.6 to 1.2 lb/t (mid 0.9), S 1.2 lb/t; lb per short ton x 0.5 = kg per tonne, Ca and Mg then converted to CaO (x1.399) and MgO (x1.658). Rate: From a Philippine study of Ilocos tomato farmers: Northern Foods Corporation recommends 116-40-120 kg NPK/ha for processing tomato and PCAARRD\'s blanket recommendation is 165-95-215. The abstract does not say whether P and K are elemental or oxide; treat as N-P2O5-K2O with that caveat. Farmers used 106-21-68 to 123-57-151. Yield: FAOSTAT item \'Tomatoes\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'AGRIS, Nutrient management practices of processing-type and table-type tomato farmers in Ilocos Provinces',
                    'url' => 'https://agris.fao.org/search/ar/records/647473a82d3f560f80ab9468',
                ],
                [
                    'label' => 'IPNI / Plant Nutrition Canada, 4R Plant Nutrition Manual, Table 4.1 total nutrient uptake and Table 4.5 nutrient removal (metric)',
                    'url' => 'https://plantnutrition.ca/wp-content/uploads/2022/12/Metric-4_1-4_5-0115.pdf',
                ],
                [
                    'label' => 'Yara (US), Tomato nutritional summary',
                    'url' => 'https://www.yara.us/crop-nutrition/tomato/nutritional-summary/',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'eggplant' => [
            'uptakePerTon' => ['N' => 5.17, 'P2O5' => 1.15, 'K2O' => 8.5],
            'recommendedPerHa' => ['N' => [70, 70], 'P2O5' => [70, 70], 'K2O' => [70, 70]],
            'typicalYield' => ['lo' => 10.84, 'hi' => 11.45, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: total plant uptake at 40 t/ha (N 207, P2O5 46, K2O 340, S 15 kg/ha; IFA, Paterson 1989); divided by 40. IFA says the S value is an estimate from N:S ratios. Rate: DA RFO V Bicol: 10 sacks of 14-14-14 per ha basal (10 x 50 kg x 14 percent), or 25 g per hill, less if compost is applied. DA RFO 02 gives per-bed-length rates (0.4 kg 16-20-0 plus 0.4 kg ammonium sulfate plus 0.1 kg potash per 10 linear m basal, then urea and potash side dressings) that I could not convert without bed spacing. Yield: FAOSTAT item \'Eggplants (aubergines)\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'DA RFO 02 Cagayan Valley Eggplant Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Eggplant.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'ampalaya' => [
            'recommendedPerHa' => ['N' => [44, 89.3], 'P2O5' => [21, 28], 'K2O' => [21, 88]],
            'about' => 'Rate: DA RFO 02 ampalaya cost sheet: 3 bags 14-14-14 plus 1 bag urea per ha with 20 bags organic fertilizer (N 21+23 = 44, P2O5 21, K2O 21), and a per-hill rate of 20 g 14-14-14 basal plus 10 g urea side dressing, repeated. DA RFO V Bicol: 30 g complete fertilizer per plant basal, then 20 g urea and 15 g potash per plant, repeated every 25 days, at 100 x 150 cm spacing (6,667 plants/ha): basal 28-28-28 plus 61 N and 60 K2O per side dressing. The high end shown is basal plus one side dressing; each repeat adds that much again.',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Ampalaya Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Ampalaya.pdf',
                ],
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
            ],
        ],
        'squash' => [
            'uptakePerTon' => ['N' => 17.5, 'P2O5' => 5.6, 'K2O' => 17.4],
            'recommendedPerHa' => ['N' => [37, 58], 'P2O5' => [14, 35], 'K2O' => [35, 44]],
            'efficiency' => ['N' => 0.36, 'P2O5' => 0.21, 'K2O' => 0.86],
            'typicalYield' => ['lo' => 12.72, 'hi' => 13.91, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: STCR (soil test crop response) \'nutrient requirement for one quintal of pumpkin\', Cucurbita moschata, Orissa, India. This is a regression-derived requirement, not measured plant uptake, and it is high next to other crops; treat with care. Rate: DA RFO 02 squash cost sheet: 2 bags 14-14-14, 1 bag urea, 1 bag 0-0-60 per ha (N 37, P2O5 14, K2O 44). DA RFO V Bicol: 5 bags 14-14-14 basal plus 1 bag urea 40 days later (N 58, P2O5 35, K2O 35), up to 15 bags 14-14-14 where soil analysis calls for it. Yield: FAOSTAT item \'Pumpkins, squash and gourds\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'Gogoi and Mishra 2015, Evaluation of STCR targeted yield approach on pumpkin, Indian J. Tropical Agriculture 33(2)',
                    'url' => 'https://serialsjournals.com/abstract/52081_248.pdf',
                ],
                [
                    'label' => 'DA RFO 02 Cagayan Valley Squash Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Squash.pdf',
                ],
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
            ],
        ],
        'cucumber' => [
            'uptakePerTon' => ['N' => 1.95, 'P2O5' => 1.35, 'K2O' => 3.5],
            'recommendedPerHa' => ['N' => [60, 74], 'P2O5' => [14, 28], 'K2O' => [14, 58]],
            'typicalYield' => ['lo' => 6.88, 'hi' => 7.62, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: total uptake at 20 t/ha outdoors (N 39, P2O5 27, K2O 70, MgO 10, CaO 35 kg/ha; IFA \'various sources\'); divided by 20. Rate: DA RFO 02 cost sheet: 2 bags 14-14-14 and 2 bags urea per ha (N 60, P2O5 14, K2O 14). DA RFO V Bicol: 4 bags 14-14-14 basal, then 2 bags urea and 1 bag 0-0-60 at the first side dressing (N 74, P2O5 28, K2O 58). Yield: FAOSTAT item \'Cucumbers and gherkins\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Cucumber Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Cucumber-Production-Guide.pdf',
                ],
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'okra' => [
            'uptakePerTon' => ['N' => 10, 'P2O5' => 3.65, 'K2O' => 7.8],
            'recommendedPerHa' => ['N' => [134, 194], 'P2O5' => [42, 56], 'K2O' => [42, 56]],
            'typicalYield' => ['lo' => 7.45, 'hi' => 8, 'unit' => 't/ha pods'],
            'about' => 'Uptake: total plant uptake at 20 t/ha pods (N 200, P2O5 73, K2O 156, MgO 45, CaO 38 kg/ha; IFA). IFA says the vegetative part was assumed (pods 45 percent of dry weight), so this is an estimate. Pods alone: N 79, P2O5 32, K2O 89 kg/ha. Rate: DA RFO V Bicol: 6 to 8 bags of 14-14-14 plus 4 to 6 bags of 46-0-0 per ha without soil analysis. DA RFO 02 is lower: 2 to 3 bags of 14-14-14 plus 20 bags organic fertilizer and 10 g urea per hill at 30 days after planting. Yield: FAOSTAT item \'Okra\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'DA RFO 02 Cagayan Valley Okra Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Okra.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'chili' => [
            'uptakePerTon' => ['N' => 3.33, 'P2O5' => 0.76, 'K2O' => 4.38],
            'recommendedPerHa' => ['N' => [173, 173], 'P2O5' => [68, 68], 'K2O' => [208, 208]],
            'typicalYield' => ['lo' => 4.49, 'hi' => 5.18, 'unit' => 't/ha green fruit'],
            'proxy' => 'bell pepper figures; no hot chili uptake table was opened',
            'about' => 'Uptake: PROXY: IFA Capsicum annuum var. grossum (bell pepper), total uptake at 21 t/ha (N 70, P2O5 16, K2O 92, MgO 18, CaO 67 kg/ha); divided by 21. Rate: DA RFO 02 Pepper Production Guide, Table 2: basal 4 bags 14-14-14 plus 4 bags 16-20-0; 10 days after transplanting 2 bags ammonium sulfate; 30 days 2 bags urea and 2 bags 0-0-60; 50 days 2 bags urea and 4 bags 0-0-60 (per ha). Totals computed from 50 kg bags: N 173, P2O5 68, K2O 208. Yield: FAOSTAT item \'Chillies and peppers, green (Capsicum spp. and Pimenta spp.)\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Pepper Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Pepper.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'bellpepper' => [
            'uptakePerTon' => ['N' => 3.33, 'P2O5' => 0.76, 'K2O' => 4.38],
            'recommendedPerHa' => ['N' => [60, 100], 'P2O5' => [14, 200], 'K2O' => [74, 100]],
            'typicalYield' => ['lo' => 4.49, 'hi' => 5.18, 'unit' => 't/ha green fruit'],
            'about' => 'Uptake: total uptake at 21 t/ha (N 70, P2O5 16, K2O 92, MgO 18, CaO 67 kg/ha; IFA, Capsicum annuum var. grossum, tropical/subtropical); divided by 21. Rate: DA RFO 02 bell pepper cost sheet: 2 bags 14-14-14, 2 bags urea, 2 bags 0-0-60 per ha (N 60, P2O5 14, K2O 74); the text also says 1 tbsp 14-14-14 per hill equals 5 to 7 bags/ha. Benguet State University: 100-200-100 plus boron gave the heaviest yield. The P2O5 range is wide because the two sources differ. Yield: FAOSTAT item \'Chillies and peppers, green (Capsicum spp. and Pimenta spp.)\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO 02 Cagayan Valley Bell Pepper Production Guide',
                    'url' => 'https://cagayanvalley.da.gov.ph/wp-content/uploads/2018/02/Bellpepper.pdf',
                ],
                [
                    'label' => 'Benguet State University, Balanced Fertilization Strategy for semi-temperate vegetables in the highlands (abstract)',
                    'url' => 'https://journals.bsu.edu.ph/mjsir/article/view/225',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
            ],
        ],
        'watermelon' => [
            'uptakePerTon' => ['N' => 3.73, 'P2O5' => 1.07, 'K2O' => 6.67],
            'recommendedPerHa' => ['N' => [14, 21], 'P2O5' => [14, 21], 'K2O' => [14, 21]],
            'typicalYield' => ['lo' => 11.8, 'hi' => 17.99, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: total uptake at 15 t/ha (N 56, P2O5 16, K2O 100, MgO 25, CaO 98 kg/ha; IFA \'various sources\'); divided by 15. Rate: DA (ATI Region 7 Watermelon Production Guide): 100 to 150 kg of complete fertilizer per ha at planting plus 10 to 15 t/ha manure; nitrogen side dressing if plants yellow. The guide does not give the grade; read as 14-14-14 this is 14 to 21 kg of each nutrient, which is low. Yield: FAOSTAT item \'Watermelons\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA ATI-7 Watermelon Production Guide',
                    'url' => 'https://ati2.da.gov.ph/ati-7/content/sites/default/files/users/user16/Watermelon%20Production%20Guide.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'onion' => [
            'uptakePerTon' => ['N' => 2.49, 'P2O5' => 1, 'K2O' => 2.73],
            'recommendedPerHa' => ['N' => [222, 222], 'P2O5' => [84, 84], 'K2O' => [84, 84]],
            'typicalYield' => ['lo' => 9.64, 'hi' => 12.48, 'unit' => 't/ha dry bulbs'],
            'about' => 'Uptake: total uptake at 41 t/ha (N 102, P2O5 41, K2O 112, MgO 17, CaO 29 kg/ha; IFA \'various sources\'); divided by 41. Rate: DA RFO V Bicol: 12 bags of 14-14-14 and 6 bags of 46-0-0 per ha (N 84+138 = 222, P2O5 84, K2O 84), with 20 to 25 t/ha compost. Yield: FAOSTAT item \'Onions and shallots, dry (excluding dehydrated)\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'garlic' => [
            'uptakePerTon' => ['N' => 19.25, 'P2O5' => 3.4, 'K2O' => 15.4],
            'recommendedPerHa' => ['N' => [75, 105], 'P2O5' => [17.5, 37.3], 'K2O' => [17.5, 37.3]],
            'typicalYield' => ['lo' => 2.39, 'hi' => 2.85, 'unit' => 't/ha'],
            'about' => 'Uptake: STCR (soil test crop response) nutrient requirement per quintal of bulb yield in two Indian Inceptisol studies (JISSS 2013 and 2023); regression-derived requirement, not measured uptake. Rate: DA RFO V Bicol: without soil analysis a 1:1 mix of 14-14-14 and urea (5 to 7 bags) or a 2:1 mix (7 to 8 bags), 2 to 3 splits, plus 500 to 1,000 kg/ha organic fertilizer. I read the bag counts as the total of the mix; the original wording is ambiguous. Yield: FAOSTAT item \'Green garlic\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'AGRIS, Response of garlic to integrated nutrient management based on targeted yield concept in Inceptisol (JISSS 2013)',
                    'url' => 'https://agris.fao.org/search/fr/records/6582f7b0de2dcdb4f6750d9e',
                ],
                [
                    'label' => 'JISSS 71(3) 2023, soil test based fertilizer prescriptions for garlic in an Inceptisol of eastern Uttar Pradesh',
                    'url' => 'https://epubs.icar.org.in/index.php/JISSS/article/view/145969',
                ],
                [
                    'label' => 'DA RFO V (Bicol) Guiya sa Gulay 2021, vegetable production guide (bags per hectare), hosted by DA HVCDP',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Guiya-sa-Gulay-2021.pdf',
                ],
            ],
        ],
        'sugarcane' => [
            'uptakePerTon' => ['N' => 1.39, 'P2O5' => 0.38, 'K2O' => 2.71],
            'typicalYield' => ['lo' => 46.17, 'hi' => 62.53, 'unit' => 't cane/ha'],
            'about' => 'Uptake: total uptake; mean of IFA rows (India 1.2/0.46/1.44 N/P2O5/K2O, Brazil 0.8/0.30/1.32, South Africa 1.75/0.41/6.0) and IPNI Table 4.1 China (1.8/0.36/2.1); MgO and CaO from the Brazil and South Africa rows, S from Brazil. Yield: FAOSTAT item \'Sugar cane\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'IPNI / Plant Nutrition Canada, 4R Plant Nutrition Manual, Table 4.1 total nutrient uptake and Table 4.5 nutrient removal (metric)',
                    'url' => 'https://plantnutrition.ca/wp-content/uploads/2022/12/Metric-4_1-4_5-0115.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'pineapple' => [
            'uptakePerTon' => ['N' => 3.73, 'P2O5' => 1.05, 'K2O' => 7.15],
            'typicalYield' => ['lo' => 40.42, 'hi' => 43.23, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: total plant uptake at 55 t/ha (N 205, P2O5 58, K2O 393, MgO 42, CaO 121 kg/ha; IFA, Martin-Prevel 1961); divided by 55. Yield: FAOSTAT item \'Pineapples\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'banana' => [
            'uptakePerTon' => ['N' => 5.5, 'P2O5' => 1.25, 'K2O' => 24],
            'recommendedPerHa' => ['N' => [90, 90], 'P2O5' => [30, 30], 'K2O' => [120, 120]],
            'typicalYield' => ['lo' => 30.28, 'hi' => 33.35, 'unit' => 't/ha fruit'],
            'about' => 'Uptake: total net uptake for Cavendish at harvest (IFA): N 4 to 7, P2O5 0.9 to 1.6, K2O 18 to 30, MgO 1.2 to 3.6, CaO 3 to 7.5, S 0.4 to 0.8 kg per t of whole bunches; the values shown are midpoints. Other varieties up to N 10, P2O5 3.5, K2O 60. Rate: DA HVCDP Banana Production Manual: without soil or leaf analysis use 90-30-120 NPK (rule of thumb 2:1:3), monthly applications. The manual does not say whether it is per year or whether P and K are oxides. Yield: FAOSTAT item \'Bananas\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'DA HVCDP Banana Production Manual',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Banana-Production-Manual.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'papaya' => [
            'uptakePerTon' => ['N' => 1.77, 'P2O5' => 0.5, 'K2O' => 2.55],
            'typicalYield' => ['lo' => 19.21, 'hi' => 21.73, 'unit' => 't/ha fruit'],
            'removalOnly' => true,
            'about' => 'Uptake: nutrients EXPORTED in harvested fruit only (not whole-plant uptake): per tonne N 1.77 kg, P 0.22 kg, K 2.12 kg, Ca 0.35 kg, Mg 0.18 kg, S 0.20 kg; P, K, Ca, Mg converted to oxides (Cunha and Haag 1980, Sao Paulo, Brazil). Yield: FAOSTAT item \'Papayas\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'Cunha and Haag 1980, Mineral nutrition of papaya tree IV: fruit development and nutrient exportation by harvesting (UNESP repository)',
                    'url' => 'https://acervodigital.unesp.br/handle/11449/26713',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'mango' => [
            'uptakePerTon' => ['N' => 1.07, 'P2O5' => 0.53, 'K2O' => 2.42],
            'efficiency' => ['N' => 0.4, 'P2O5' => 0.4, 'K2O' => 0.6],
            'typicalYield' => ['lo' => 3.73, 'hi' => 4.18, 'unit' => 't/ha fruit'],
            'removalOnly' => true,
            'about' => 'Uptake: nutrients removed in harvested fruit only (Haden and Tommy Atkins, Michoacan, Mexico): per tonne N 1.03 to 1.11, P 0.22 to 0.24, K 1.88 to 2.14, Ca 0.21 to 0.31, Mg 0.14 to 0.15, S 0.28 to 0.33 kg; mid values, P, K, Ca, Mg converted to oxides. Yield: FAOSTAT item \'Mangoes, guavas and mangosteens\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'Fruit nutrient composition and removal by Haden and Tommy Atkins mangos (Revista Mexicana de Ciencias Agricolas)',
                    'url' => 'https://cienciasagricolas.inifap.gob.mx/index.php/agricolas/article/view/1384',
                ],
                [
                    'label' => 'NT Government (Australia), Mango nutrition part 2 slides (nutrient removal and efficiency)',
                    'url' => 'https://industry.nt.gov.au/__data/assets/pdf_file/0007/267469/Mango_Nutrit_part2.pdf',
                ],
                [
                    'label' => 'DA HVCDP Giya sa Pagpananum ug Manga (per-tree rates)',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Giya-sa-Pagpananum-ug-Manga-with-cover.pdf',
                ],
            ],
        ],
        'coconut' => [
            'uptakePerTon' => ['N' => 16.2, 'P2O5' => 5, 'K2O' => 36],
            'recommendedPerHa' => ['N' => [31.5, 63], 'K2O' => [0, 135]],
            'treesPerHa' => 150,
            'typicalYield' => ['lo' => 3.88, 'hi' => 4.14, 'unit' => 't nuts in shell/ha/yr'],
            'removalOnly' => true,
            'about' => 'Uptake: nutrients removed in the nuts, per tonne of copra (IFA, Ashgar 1988): N 16.2, P2O5 5, K2O 36, Mg 2, Ca 1.4, S 1.3. Cross-check: Ouvier and Ochs 1978, 150 palms/ha at 100 nuts per palm: N 49, P2O5 16, K2O 115 kg/ha per year in the harvest, i.e. N 3.3, P2O5 1.1, K2O 7.7 kg per 1,000 nuts, and nuts only for a 6.7 t copra crop N 108, P2O5 39, K2O 232 kg/ha (16.1, 5.8, 34.6 per t copra). Rate: Philippine Coconut Authority (Davao Research Center) trial: lower recommended dose 1.0 kg ammonium sulfate (21 percent N = 0.21 kg N) plus 1.8 kg common salt (chloride, no NPK) per palm per year. Leyte trial (Visayas State): up to 2.0 kg ammonium sulfate (0.42 kg N) plus 1.5 kg muriate of potash (0.9 kg K2O) per palm per year. Tree density 150 palms/ha is the IFA/Ouvier and Ochs figure, not a PCA one. Yield: FAOSTAT item \'Coconuts, in shell\', Philippines national average yield, range of annual v',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'AGRIS, Response to integrated soil fertility management of hybrid coconut on an inland soil of South Cotabato (PCA)',
                    'url' => 'https://agris.fao.org/search/en/records/647226ff77fd37171a72f2d5',
                ],
                [
                    'label' => 'AGRIS, Yield of seven dwarf coconut cultivars under four ammonium sulfate plus potassium chloride levels, Leyte',
                    'url' => 'https://agris.fao.org/search/en/records/64722afe77fd37171a735b82',
                ],
            ],
        ],
        'calamansi' => [
            'uptakePerTon' => ['N' => 1.64, 'P2O5' => 0.37, 'K2O' => 2.09],
            'typicalYield' => ['lo' => 5.24, 'hi' => 6.42, 'unit' => 't/ha fruit'],
            'removalOnly' => true,
            'proxy' => 'lemon and lime citrus fruit; calamansi (calamondin) is not listed',
            'about' => 'Uptake: nutrients removed in harvested fruit only, lemon and lime row of the IFA citrus table (Koo 1958, Chapman 1968, Malavolta 1989); mandarin row is N 1.53, P2O5 0.38, K2O 2.47. Yield: FAOSTAT item \'Other citrus fruit, n.e.c.\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'DA ATI-4B Calamansi production guide',
                    'url' => 'https://ati2.da.gov.ph/ati-4b/content/sites/default/files/2022-12/calamansi_final.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'coffee' => [
            'uptakePerTon' => ['N' => 33.93, 'P2O5' => 5.9, 'K2O' => 48.78],
            'recommendedPerHa' => ['N' => [308.9, 308.9], 'P2O5' => [155.5, 155.5], 'K2O' => [155.5, 155.5]],
            'treesPerHa' => 1111,
            'typicalYield' => ['lo' => 0.53, 'hi' => 0.55, 'unit' => 't/ha green bean'],
            'removalOnly' => true,
            'about' => 'Uptake: nutrients removed in whole fruit equivalent to 1,000 kg green bean (IFA: Arabica Brazil/Kenya/India, Robusta India/Ivory Coast/Indonesia); mean of six rows (MgO and CaO of four rows). Rate: DA HVCDP coffee guide (Filipino and Cebuano editions): trees not yet bearing, equal NPK plus ammonium sulfate or urea at 250 to 300 g per tree per year; bearing trees (7 years and up) 1 kg of 14-14-14 per tree per year plus 300 g urea per tree per year = 0.14 kg each of N, P2O5, K2O plus 0.138 kg N from urea (0.278 kg N total). Trees per ha computed from the guide\'s spacings: Arabica 3x1 to 3x2 m, Robusta 3x1.5 to 3x3 m, Liberica and Excelsa 4x5 to 5x5.5 m. The non-bearing N, P2O5, K2O split is not given, so only the bearing rate is exact. Yield: FAOSTAT item \'Coffee, green\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures). The rat',
            'sources' => [
                [
                    'label' => 'DA HVCDP Coffee Production Guide',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/Coffee-Production-guide.pdf',
                ],
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'cacao' => [
            'uptakePerTon' => ['N' => 36.4, 'P2O5' => 13.33, 'K2O' => 83.83],
            'typicalYield' => ['lo' => 0.28, 'hi' => 0.33, 'unit' => 't/ha dry beans'],
            'removalOnly' => true,
            'about' => 'Uptake: nutrients in a crop of 1 t/ha dry beans with 1.4 t/ha husks (IFA): totals for Cameroon, Ivory Coast and Nigeria; mean (MgO and CaO of two countries). Yield: FAOSTAT item \'Cocoa beans\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual (1992), crop chapters (nutrient demand/uptake/removal tables)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'DA HVCDP Cacao Production Guide',
                    'url' => 'https://hvcdp.da.gov.ph/wp-content/uploads/2022/05/CACAO-Production-Guide.pdf',
                ],
                [
                    'label' => 'FAOSTAT crops and livestock products, bulk file for Asia (Philippines yield element)',
                    'url' => 'https://bulks-faostat.fao.org/production/Production_Crops_Livestock_E_Asia.zip',
                ],
            ],
        ],
        'rice_dsr_wet' => [
            'uptakePerTon' => ['N' => 22.2, 'P2O5' => 7.1, 'K2O' => 31.6],
            'recommendedPerHa' => ['N' => [97, 139], 'P2O5' => [64.2, 80.2], 'K2O' => [51.8, 60.2]],
            'efficiency' => ['N' => 0.4, 'P2O5' => 0.2, 'K2O' => 0.35],
            'typicalYield' => ['lo' => 3.97, 'hi' => 4.17, 'unit' => 't/ha palay'],
            'about' => 'Uptake: total above-ground uptake, grain plus straw (IR36, Laguna, Philippines). Rate: PhilRice modified general recommendation for irrigated lowland (fixed-rate fixed-time): wet season N 97, P 28, K 43; dry season N 139, P 35, K 50 kg/ha. The table is headed \'Nutrient Element\' so P and K were converted to P2O5 (x2.291) and K2O (x1.205). Yield: FAOSTAT item \'Rice\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual, Rice chapter (De Datta 1989, IR36 in the Philippines)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'PhilRice, Reinforcing right E-A-T for improved fertilizer application (Table 1, modified general recommendation)',
                    'url' => 'https://www.philrice.gov.ph/reinforcing-right-e-a-t-for-improved-fertilizer-application',
                ],
                [
                    'label' => 'Sta. Cruz (UPLB), Nutrient management in improving the productivity of lowland rice in the Philippines, SEARCA 2011 slides',
                    'url' => 'https://www.searca.org/~searca/phocadownload/ADSS_2011/adss-Nutrient%20Management%20in%20Improving%20the%20Productivity%20of%20Lowland%20Rice%20in%20the%20Philippines-2011-jun-28.pdf',
                ],
            ],
        ],
        'rice_dsr_dry' => [
            'uptakePerTon' => ['N' => 22.2, 'P2O5' => 7.1, 'K2O' => 31.6],
            'recommendedPerHa' => ['N' => [97, 139], 'P2O5' => [64.2, 80.2], 'K2O' => [51.8, 60.2]],
            'efficiency' => ['N' => 0.4, 'P2O5' => 0.2, 'K2O' => 0.35],
            'typicalYield' => ['lo' => 3.97, 'hi' => 4.17, 'unit' => 't/ha palay'],
            'about' => 'Uptake: total above-ground uptake, grain plus straw (IR36, Laguna, Philippines). Rate: PhilRice modified general recommendation for irrigated lowland (fixed-rate fixed-time): wet season N 97, P 28, K 43; dry season N 139, P 35, K 50 kg/ha. The table is headed \'Nutrient Element\' so P and K were converted to P2O5 (x2.291) and K2O (x1.205). Yield: FAOSTAT item \'Rice\', Philippines national average yield, range of annual values 2018 to 2024 (FAOSTAT carries PSA-reported figures).',
            'sources' => [
                [
                    'label' => 'IFA World Fertilizer Use Manual, Rice chapter (De Datta 1989, IR36 in the Philippines)',
                    'url' => 'https://www.fertilizer.org/wp-content/uploads/1992/06/IFA_World_Fertilizer_Use_Manual.pdf',
                ],
                [
                    'label' => 'PhilRice, Reinforcing right E-A-T for improved fertilizer application (Table 1, modified general recommendation)',
                    'url' => 'https://www.philrice.gov.ph/reinforcing-right-e-a-t-for-improved-fertilizer-application',
                ],
                [
                    'label' => 'Sta. Cruz (UPLB), Nutrient management in improving the productivity of lowland rice in the Philippines, SEARCA 2011 slides',
                    'url' => 'https://www.searca.org/~searca/phocadownload/ADSS_2011/adss-Nutrient%20Management%20in%20Improving%20the%20Productivity%20of%20Lowland%20Rice%20in%20the%20Philippines-2011-jun-28.pdf',
                ],
            ],
        ],
    ];
}
